### ISSUE TITLE
Preserve section order

### ISSUE THREAD

**Issue by mmhat** [chrisdone/ini#25]
There are some INI files where the order of the sections is relevant.
Look for example at the [pacman.conf](https://wiki.archlinux.org/index.php/Pacman#Configuration) of the Arch Linux package manager (which is my use case).
I don't think giving up on the HashMap as an underlying datastructure is the right way since it's sufficient for probably most of the use cases, but would an order-preserving version in a separate module be acceptable? Or a parameterized Ini type and Ini simply be a type alias like
```
newtype Ini' f = Ini' { unIni :: f Text (HashMap Text Text) }
type Ini = Ini' HashMap
```
If there's any chance such an extension were accepted I'd volunteer for the implementation.
Thanks!

**Comment by joehillen** [comment]
As you say, it's a pretty simple change to make sections ordered. https://github.com/joehillen/ini/commit/c5df57297cff1f05dd016bf0a0aafd7fa936416b Unfortunately, `unIni` is exposed so there is no guarantee that it won't cause a type error for anybody.

I recommend forking the package into something like `ordered-ini`.

Another option might be to convert ini to use [unpacked-containers](https://hackage.haskell.org/package/unpacked-containers) so then unordered-containers can be swapped out for whatever.
