### ISSUE TITLE
Ini file returning an empty Ini structure?

### ISSUE THREAD

**Issue by mwm** [chrisdone/ini#6]
Sorry for the lack of narrowing this down, but I didn't want to just let things pass without letting you know about this issue. If you want to flag this as an unsupported format and close it, that'd be fine by me.

I'm trying to parse ini files from deviationTx (deviationTx.com), which uses some odd features of the ini file format. Tried feeding one to readIniFile to see if I could use this Data.Ini, and got back an empty list (Right (Ini {unIni = fromList []}).

**Comment by mwm** [comment]
Huh. No file attach facility. Oh well, here's the .ini file in question. And yes, it starts with values instead of a section header.


name=Phoenix
mixermode=Advanced
icon=CHAMP.BMP
[radio]
protocol=PPM
num_channels=6
fixed_id=123456
tx_power=150mW

[protocol_opts]
Center PW=1100
Delta PW=400
Notch PW=400
Frame Size=22500

[channel1]
template=expo_dr
[mixer]
src=AIL
dest=Ch1
[mixer]
src=AIL
dest=Ch1
switch=AIL DR1
scalar=70

[channel2]
template=expo_dr
[mixer]
src=ELE
dest=Ch2
[mixer]
src=ELE
dest=Ch2
switch=AIL DR1
scalar=70

[channel3]
safetysw=Virt1
safetyval=-100
template=expo_dr
[mixer]
src=THR
dest=Ch3
[mixer]
src=THR
dest=Ch3
switch=!FMODE0
curvetype=fixed
[mixer]
src=THR
dest=Ch3
switch=ELE DR1

[channel4]
template=expo_dr
[mixer]
src=RUD
dest=Ch4
[mixer]
src=RUD
dest=Ch4
switch=AIL DR1
scalar=70

[channel5]
template=complex
[mixer]
src=AUX4
dest=Ch5
scalar=0
usetrim=0
curvetype=fixed
[mixer]
src=MIX2
dest=Ch5
switch=!MIX1
usetrim=0
curvetype=min/max
points=0
[mixer]
src=GEAR1
dest=Ch5
switch=ELE DR1
curvetype=min/max
points=0

[channel6]
template=complex
[mixer]
src=THR
dest=Ch6
switch=FMODE0
scalar=-100
usetrim=0
curvetype=fixed
[mixer]
src=THR
dest=Ch6
switch=FMODE1
scalar=0
usetrim=0
curvetype=fixed
[mixer]
src=FMODE0
dest=Ch6
switch=FMODE2
usetrim=0
curvetype=fixed
[mixer]
src=Virt3
dest=Ch6
switch=ELE DR0
usetrim=0

[channel7]
template=simple
[mixer]
src=AUX4
dest=Ch7

[channel8]
template=complex
[mixer]
src=AUX5
dest=Ch8
usetrim=0
[mixer]
src=MIX2
dest=Ch8
switch=!MIX1
usetrim=0
curvetype=min/max
points=0
[mixer]
src=AUX5
dest=Ch8
switch=ELE DR0

[channel9]
template=expo_dr
[mixer]
src=ELE
dest=Ch9
curvetype=expo
points=35,35
[mixer]
src=ELE
dest=Ch9
switch=AIL DR1
scalar=70

[virtchan1]
template=complex
[mixer]
src=Virt1
dest=Virt1
usetrim=0
curvetype=min/max
points=0
[mixer]
src=Ch3
dest=Virt1
offset=-1
usetrim=0
muxtype=add
[mixer]
src=AIL
dest=Virt1
switch=RUD DR1
usetrim=0
curvetype=fixed

[virtchan3]
name=Pitch
template=complex
[mixer]
src=THR
dest=Virt3
scalar=55
offset=45
usetrim=0
[mixer]
src=THR
dest=Virt3
switch=FMODE2
usetrim=0

[trim1]
src=LEFT_V
pos=TRIMLV+
neg=TRIMLV-
[trim2]
src=RIGHT_V
pos=TRIMRV+
neg=TRIMRV-
[trim3]
src=LEFT_H
pos=TRIMLH+
neg=TRIMLH-
[trim4]
src=RIGHT_H
pos=TRIMRH+
neg=TRIMRH-
value=1,0,0
[trim5]
src=AUX4
pos=TRIM_L-
neg=TRIM_L+
[trim6]
src=AUX5
pos=TRIM_R-
neg=TRIM_R+
[timer2]
type=permanent
val=900
[datalog]
switch=None
rate=1 sec
[safety]
Auto=min
[gui-128x64]
V-trim=59,10,1
H-trim=5,59,3
V-trim=65,10,2
H-trim=74,59,4
Small-box=2,22,Ch3
Small-box=2,31,Timer1
Small-box=2,40,Timer2
Model=75,20
Battery=102,1
Toggle=4,10,0,72,0,Virt1
Toggle=13,10,0,67,0,ELE DR
Toggle=22,10,0,69,0,AIL DR
Toggle=31,10,1,134,194,FMODE
Toggle=40,10,0,71,0,GEAR
TxPower=102,7
quickpage1=Channel monitor

**Comment by chrisdone** [comment]
Every property set must be in a group. I see you also have duplicate properties, which doesn't match the `Ini` type: `HashMap Text (HashMap Text Text)`

**Comment by mwm** [comment]
Unfortunately, the structure of the file is fixed. That the ini package doesn't handle this isn't a bug. That it silently discards data  is. If there's an option to make it complain about those, it probably ought to be the default.

**Comment by dtchepak** [comment]
I've found some references to a "default section" (for example, see [Implementation Details](http://commons.apache.org/proper/commons-configuration/javadocs/v1.10/apidocs/index.html?org/apache/commons/configuration/HierarchicalINIConfiguration.html)). It looks like properties outside a section are available via any section unless overridden?

Wikipedia [also suggests sections are optional](https://en.wikipedia.org/wiki/INI_file#Sections)<sup>_[citation needed]_</sup>.

I'd be happy to try to write a patch to add this if you think it is worth considering?

**Comment by chrisdone** [comment]
What would the returned type be for such a parse? We currently have a map from section name to properties.

**Comment by dtchepak** [comment]
I was thinking of having an empty section name (`""`) refer to the global section.

**Comment by chrisdone** [comment]
Pretty gross?

**Comment by dtchepak** [comment]
Yes, especially on lookup, although I don't think it is too great a stretch to say it meets the requirement for a global section to be a section without a name, and would mean we could add the feature without breaking existing code.[1]

Could switch section name to `Maybe` if we want  difference between a `Nothing` section name and `Just ""`. Or have a tuple of `(HashMap Text Text, HashMap Text (HashMap Text Text))` to further distinguish the global section. Would then want to change the lookup/read API as well to indicate whether we want the global or named sections?

-------
[1] INIs with existing empty sections `[]` would continue to work the same, as duplicate keys get overridden with the current implementation:
```
ghci> parseIni "[]\a=1\n[]\b=2"
Right (Ini {unIni = fromList [("",fromList [("\b","2")])]})
```

**Comment by fpcomplete-support** [comment]
Using an empty string to represent not having a value is what you'd have to do if your type system isn't up to snuff. The type here should be `Maybe String`, with `Nothing` for the default section. At least, the API should be that way, the data structure could be a `Map (Maybe String) Section` or `Section (Map String Section)`. The API can then use whatever is convenient: functions that deal explicitly with default, functions that select named sections that take a `String`, and functions that could use either taking a `Maybe String`. All the old API's should be the middle one, and you add the first and last. Not sure about how you expose the top-level map now, but that might create compatibility issues moving forwards.

**Comment by 3noch** [comment]
> Using an empty string to represent not having a value is what you'd have to do if your type system isn't up to snuff.

It depends on how you look at it, really. It's not entirely novel to think of the "global" section as the "unnamed" section. C++ does it with namespaces (e.g. `::func` is in the global namespace and `std::func` is in the `std` namespace).

**Comment by 3noch** [comment]
@mwm Perhaps you could pull your file in and pre-pend `"[_global_]\n"` to it. That would at least get you in the ballpark.

**Comment by 3noch** [comment]
@chrisdone Perhaps you could offer a `compat` module with alternative parsers for such things? As long as your clear about how a parse results in a `HashMap Text (HashMap Text Text))`, folks should be able to work with it.

**Comment by chrisdone** [comment]
>  Perhaps you could offer a compat module with alternative parsers for such things? As long as you're clear about how a parse results in a HashMap Text (HashMap Text Text)), folks should be able to work with it.

The parsers are already exposed [here](http://hackage.haskell.org/package/ini-0.3.2/docs/Data-Ini.html#g:4), so you could just do `(,) <$> many keyValueParser <*> iniParser`.

> Using an empty string to represent not having a value is what you'd have to do if your type system isn't up to snuff. The type here should be Maybe String

We can also just have `Ini` have two fields; a set of sections and a set of [global properties](https://en.wikipedia.org/wiki/INI_file#Global_properties). I think that's nice because it saves a lookup. E.g.

    case M.lookup Nothing ini of 
      Just global -> case M.lookup "key" global of ...

Instead you could just lookup in the global directly with e.g. `M.lookup (iniGlobal ini)`.

**Comment by chrisdone** [comment]
OK, now key/values are supported before the first section, and put in `iniGlobals`, and duplicate key/values are supported by a simple `[(k,v)]` list. The existing API is preserved, but this leaves room for people to handle duplicate values with `lookupArray` and `readArray`.
